package edu.mit.puzzle.cube.huntimpl.setec2017;

import com.google.common.collect.ImmutableMap;

import edu.mit.puzzle.cube.core.model.Puzzle;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.Character;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.Setec2017PuzzleBuilder;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.SolveRewardProperty;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.VisibilityConstraint;

import java.util.function.Consumer;

public class Setec2017Puzzles {
    Setec2017Puzzles() {}

    static final ImmutableMap<String, Puzzle> PUZZLES;
    static {
        ImmutableMap.Builder<String, Puzzle> puzzlesBuilder = ImmutableMap.builder();
        Consumer<Setec2017PuzzleBuilder> add = puzzleBuilder -> {
            Puzzle puzzle = puzzleBuilder.build();
            puzzlesBuilder.put(puzzle.getPuzzleId(), puzzle);
        };

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("fighter")
                .setDisplayId("fighter")
                .setDisplayName("The Fighter")
                .setSingleAnswer("ONE-TWO COMBO"));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f1")
                .setDisplayId("before_and_after_mash")
                .setDisplayName("Before and After MASH")
                .setSingleAnswer("COULD HAVE BEEN")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f2")
                .setDisplayId("bigram_battleships")
                .setDisplayName("Bigram Battleships")
                .setSingleAnswer("HYDROCOOLS")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f3")
                .setDisplayId("crossing_your_arms")
                .setDisplayName("Crossing Your Arms")
                .setSingleAnswer("PRETEEN")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f4")
                .setDisplayId("double_crosser")
                .setDisplayName("Double-Crosser")
                .setSingleAnswer("HOUSE MEETING")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f5")
                .setDisplayId("get_her_together")
                .setDisplayName("Get Her! Together!")
                .setSingleAnswer("BOBBY HENDRICKS")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f6")
                .setDisplayId("it_takes_two")
                .setDisplayName("It Takes Two")
                .setSingleAnswer("DODD-FRANK")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f7")
                .setDisplayId("lets_get_physical")
                .setDisplayName("Let's Get Physical")
                .setSingleAnswer("LOLL")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f8")
                .setDisplayId("now_where_was_i")
                .setDisplayName("Now Where Was I?")
                .setSingleAnswer("SANAA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f9")
                .setDisplayId("swifties")
                .setDisplayName("Swifties")
                .setSingleAnswer("OBSESS")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f10")
                .setDisplayId("a_turn_of_phrase")
                .setDisplayName("A Turn of Phrase")
                .setSingleAnswer("FIREWEED")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f11")
                .setDisplayId("up_in_the_air")
                .setDisplayName("Up in the Air")
                .setSingleAnswer("MARY POPPINS")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("wizard")
                .setDisplayId("wizard")
                .setDisplayName("The Wizard")
                .setSingleAnswer("OWL FAMILIAR"));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w1")
                .setDisplayId("getting_out_of_line")
                .setDisplayName("Getting out of Line")
                .setSingleAnswer("REPRESS MEMORIES")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w2")
                .setDisplayId("a_word_from_our_sponsors")
                .setDisplayName("A Word from Our Sponsors")
                .setSingleAnswer("SEND FLYING")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w3")
                .setDisplayId("cutting_room_floor")
                .setDisplayName("Cutting Room Floor")
                .setSingleAnswer("READ MINDS")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w4")
                .setDisplayId("boston_burgers")
                .setDisplayName("Boston Burgers")
                .setSingleAnswer("COUNTER")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w5")
                .setDisplayId("unassigned_wizard_puzzle")
                .setDisplayName("Unassigned Wizard Puzzle")
                .setSingleAnswer("SUMMON")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w6")
                .setDisplayId("puzzling_is_my_middle_name")
                .setDisplayName("Puzzling Is My Middle Name")
                .setSingleAnswer("BUZZ")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w7")
                .setDisplayId("permission_to_come_aboard")
                .setDisplayName("Permission to Come Aboard")
                .setSingleAnswer("WATERPROOF")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w8")
                .setDisplayId("henna")
                .setDisplayName("Henna")
                .setSingleAnswer("ILLUMINATE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w9")
                .setDisplayId("penny_for_your_thoughts")
                .setDisplayName("Penny for Your Thoughts")
                .setSingleAnswer("CONFLAGRATE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w10")
                .setDisplayId("spell_casting")
                .setDisplayName("Spell Casting")
                .setSingleAnswer("UNLOCK")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w11")
                .setDisplayId("school_of_mines")
                .setDisplayName("School of Mines")
                .setSingleAnswer("SHRINK")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("wizard","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cleric")
                .setDisplayId("cleric")
                .setDisplayName("The Cleric")
                .setSingleAnswer("SMART BALMS"));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-l1")
                .setDisplayId("epic_raft_battles_of_history")
                .setDisplayName("Epic Raft Battles of History")
                .setSingleAnswer("SPARS")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .setGold(1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-r1")
                .setDisplayId("locked_in")
                .setDisplayName("Locked In")
                .setSingleAnswer("RIMS")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-l2")
                .setDisplayId("the_sacred_and_the_mundane")
                .setDisplayName("The Sacred and the Mundane")
                .setSingleAnswer("FANNY")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-r2")
                .setDisplayId("tavern_recognition")
                .setDisplayName("Tavern Recognition")
                .setSingleAnswer("BORE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-l3")
                .setDisplayId("pic_of_the_litter")
                .setDisplayName("Pic of the Litter")
                .setSingleAnswer("TRAIN")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-r3")
                .setDisplayId("unassigned_cleric_puzzle")
                .setDisplayName("Unassigned Cleric Puzzle")
                .setSingleAnswer("BREEZE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-l4")
                .setDisplayId("quattrocento")
                .setDisplayName("Quattrocento")
                .setSingleAnswer("WAITERS")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-r4")
                .setDisplayId("false_prophets")
                .setDisplayName("False Prophets")
                .setSingleAnswer("CLAMP")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-l5")
                .setDisplayId("china_kilns")
                .setDisplayName("China Kilns")
                .setSingleAnswer("BREAM")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(10, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl-r5")
                .setDisplayId("khaki")
                .setDisplayName("Khaki")
                .setSingleAnswer("BASSET")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("cleric","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("recruit_the_linguist")
                .setDisplayId("recruit_the_linguist")
                .setDisplayName("Recruit the Linguist")
                .setSingleAnswer("LINGUISTRECRUIT")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(12, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(12, Character.values())
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("linguist")
                .setDisplayId("linguist")
                .setDisplayName("The Linguist")
                .setSingleAnswer("SILVER TONGUE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l1")
                .setDisplayId("lead_with_hydrogen")
                .setDisplayName("Lead with Hydrogen")
                .setSingleAnswer("HOAX")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l2")
                .setDisplayId("unassigned_linguist_puzzle_1")
                .setDisplayName("Unassigned Linguist Puzzle 1")
                .setSingleAnswer("HAT")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l3")
                .setDisplayId("chaser")
                .setDisplayName("Chaser")
                .setSingleAnswer("ANTI")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(1, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l4")
                .setDisplayId("corporate_chains")
                .setDisplayName("Corporate Chains")
                .setSingleAnswer("SKOAL")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(3, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l5")
                .setDisplayId("the_gods_must_be_crazy")
                .setDisplayName("The Gods Must Be Crazy")
                .setSingleAnswer("PATERSON")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l6")
                .setDisplayId("semiotics")
                .setDisplayName("Semiotics")
                .setSingleAnswer("MANGE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(7, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l7")
                .setDisplayId("unassigned_linguist_puzzle_2")
                .setDisplayName("Unassigned Linguist Puzzle 2")
                .setSingleAnswer("MAIL")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(7, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l8")
                .setDisplayId("adactyly")
                .setDisplayName("Adactyly")
                .setSingleAnswer("SLEIGH")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(8, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l9")
                .setDisplayId("dot_matrix")
                .setDisplayName("Dot Matrix")
                .setSingleAnswer("STAPH")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(10, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l10")
                .setDisplayId("we_can_work_it_out")
                .setDisplayName("We Can Work It Out")
                .setSingleAnswer("BINAURAL")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(12, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l11")
                .setDisplayId("precipice")
                .setDisplayName("Precipice")
                .setSingleAnswer("GUEST ROPE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(14, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l12")
                .setDisplayId("sooner_or_later")
                .setDisplayName("Sooner or Later")
                .setSingleAnswer("SQUAB")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(15, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("recruit_the_economist")
                .setDisplayId("recruit_the_economist")
                .setDisplayName("Recruit the Economist")
                .setSingleAnswer("ECONOMISTRECRUIT")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(24, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(24, Character.values())
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("economist")
                .setDisplayId("economist")
                .setDisplayName("The Economist")
                .setSingleAnswer("ARCADE GAME INCOME")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e1")
                .setDisplayId("lost_in_translation")
                .setDisplayName("Lost in Translation")
                .setSingleAnswer("DIAMOND")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e2")
                .setDisplayId("pentoku")
                .setDisplayName("Pentoku")
                .setSingleAnswer("CONDOR")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e3")
                .setDisplayId("the_economists_tv_critic")
                .setDisplayName("The Economist's TV Critic")
                .setSingleAnswer("HORSEBACK RIDE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(2, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e4")
                .setDisplayId("elf_on_fire")
                .setDisplayName("Elf on Fire")
                .setSingleAnswer("PEACH")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(4, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e5")
                .setDisplayId("ye_olde_7th_duck_konundrum")
                .setDisplayName("Ye Olde 7th Duck Konundrum: The Cones of Duckshire")
                .setSingleAnswer("LIGHTHOUSE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(6, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e6")
                .setDisplayId("placeholder")
                .setDisplayName("Placeholder")
                .setSingleAnswer("RACECAR")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(6, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e7")
                .setDisplayId("local_coverage")
                .setDisplayName("Local Coverage")
                .setSingleAnswer("CENTENNIAL")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(8, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e8")
                .setDisplayId("fruitless")
                .setDisplayName("Fruitless")
                .setSingleAnswer("SCHOONER")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(11, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("recruit_the_chemist")
                .setDisplayId("recruit_the_chemist")
                .setDisplayName("Recruit the Chemist")
                .setSingleAnswer("CHEMISTRECRUIT")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(40, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(40, Character.values())
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("chemist")
                .setDisplayId("chemist")
                .setDisplayName("The Chemist")
                .setSingleAnswer("POSITIVE SPIN")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch1")
                .setDisplayId("bring_us_a_volcano")
                .setDisplayName("Bring Us a Volcano")
                .setSingleAnswer("CROC")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch2")
                .setDisplayId("somebodys_watching_me")
                .setDisplayName("Somebody's Watching Me")
                .setSingleAnswer("CONE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch3")
                .setDisplayId("hand_them_over")
                .setDisplayName("Hand Them Over!")
                .setSingleAnswer("NIOBE")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(3, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch4")
                .setDisplayId("the_great_gadsby")
                .setDisplayName("The Great Gadsby")
                .setSingleAnswer("NOES")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(5, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch5")
                .setDisplayId("out_of_the_mouths_of_babes")
                .setDisplayName("Out of the Mouths of Babes")
                .setSingleAnswer("BOY")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(7, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch6")
                .setDisplayId("amber")
                .setDisplayName("Amber")
                .setSingleAnswer("COOK")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(7, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch7")
                .setDisplayId("12_step_program")
                .setDisplayName("12-Step Program")
                .setSingleAnswer("BHOPA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(9, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch8")
                .setDisplayId("spontaneous_reactions")
                .setDisplayName("Spontaneous Reactions")
                .setSingleAnswer("KONA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(11, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch9")
                .setDisplayId("merriweather_post_pavilion")
                .setDisplayName("Merriweather Post Pavilion")
                .setSingleAnswer("CROW")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(14, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast")
                .setSingleAnswer("DYNASTMETA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.values())
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .addCharacterLevels(Character.WIZARD, 1)
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast1")
                .setSingleAnswer("DYNAST1")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast2")
                .setSingleAnswer("DYNAST2")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast3")
                .setSingleAnswer("DYNAST3")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast4")
                .setSingleAnswer("DYNAST4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast5")
                .setSingleAnswer("DYNAST5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast6")
                .setSingleAnswer("DYNAST6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast7")
                .setSingleAnswer("DYNAST7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast8")
                .setSingleAnswer("DYNAST8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast9")
                .setSingleAnswer("DYNAST9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast10")
                .setSingleAnswer("DYNAST10")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(5, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast11")
                .setSingleAnswer("DYNAST11")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(5, Character.FIGHTER)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon")
                .setSingleAnswer("DUNGEONMETA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(18, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(18, Character.values())
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .addCharacterLevels(Character.WIZARD, 1)
                        .addCharacterLevels(Character.CLERIC, 1)
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon1")
                .setSingleAnswer("DUNGEON1")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon2")
                .setSingleAnswer("DUNGEON2")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon3")
                .setSingleAnswer("DUNGEON3")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon4")
                .setSingleAnswer("DUNGEON4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(2, Character.LINGUIST)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon5")
                .setSingleAnswer("DUNGEON5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon6")
                .setSingleAnswer("DUNGEON6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon7")
                .setSingleAnswer("DUNGEON7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon8")
                .setSingleAnswer("DUNGEON8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.LINGUIST)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon9")
                .setSingleAnswer("DUNGEON9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(5, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon10")
                .setSingleAnswer("DUNGEON10")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(5, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon11")
                .setSingleAnswer("DUNGEON11")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build()));

        // TODO: add the rest of the rounds

        SolveRewardProperty.Builder solveRewardBuilder = SolveRewardProperty.builder();
        for (Character character : Character.values()) {
            solveRewardBuilder.addCharacterLevels(character, 1);
        }
        SolveRewardProperty oneLevelForEachCharacter = solveRewardBuilder.build();

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("eventa")
                .setSingleAnswer("EVENTA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveRewardProperty(oneLevelForEachCharacter));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("eventb")
                .setSingleAnswer("EVENTB")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveRewardProperty(oneLevelForEachCharacter));

        solveRewardBuilder = SolveRewardProperty.builder();
        for (Character character : Character.values()) {
            solveRewardBuilder.addCharacterLevels(character, 2);
        }
        SolveRewardProperty twoLevelsForEachCharacter = solveRewardBuilder.build();

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("eventc")
                .setSingleAnswer("EVENTC")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveRewardProperty(twoLevelsForEachCharacter));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("eventd")
                .setSingleAnswer("EVENTD")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveRewardProperty(twoLevelsForEachCharacter));

        PUZZLES = puzzlesBuilder.build();
    }
}
