package edu.mit.puzzle.cube.huntimpl.setec2017;

import com.google.common.collect.ImmutableMap;

import edu.mit.puzzle.cube.core.model.Puzzle;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.Character;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.Setec2017PuzzleBuilder;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.SolveRewardProperty;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.VisibilityConstraint;

import java.util.function.Consumer;

public class Setec2017Puzzles {
    Setec2017Puzzles() {}

    static final ImmutableMap<String, Puzzle> PUZZLES;
    static {
        ImmutableMap.Builder<String, Puzzle> puzzlesBuilder = ImmutableMap.builder();
        Consumer<Setec2017PuzzleBuilder> add = puzzleBuilder -> {
            Puzzle puzzle = puzzleBuilder.build();
            puzzlesBuilder.put(puzzle.getPuzzleId(), puzzle);
        };

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("fighter")
                .setSingleAnswer("FIGHTERMETA"));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f1")
                .setSingleAnswer("FIGHTER1")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .setGold(1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f2")
                .setSingleAnswer("FIGHTER2")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f3")
                .setSingleAnswer("FIGHTER3")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f4")
                .setSingleAnswer("FIGHTER4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f5")
                .setSingleAnswer("FIGHTER5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f6")
                .setSingleAnswer("FIGHTER6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f7")
                .setSingleAnswer("FIGHTER7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f8")
                .setSingleAnswer("FIGHTER8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f9")
                .setSingleAnswer("FIGHTER9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f10")
                .setSingleAnswer("FIGHTER10")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("f11")
                .setSingleAnswer("FIGHTER11")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("fighter","UNLOCKED").build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.FIGHTER)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("wizard")
                .setSingleAnswer("WIZARDMETA"));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w1")
                .setSingleAnswer("WIZARD1")
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .setGold(1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w2")
                .setSingleAnswer("WIZARD2")
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w3")
                .setSingleAnswer("WIZARD3")
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w4")
                .setSingleAnswer("WIZARD4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w5")
                .setSingleAnswer("WIZARD5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w6")
                .setSingleAnswer("WIZARD6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w7")
                .setSingleAnswer("WIZARD7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w8")
                .setSingleAnswer("WIZARD8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w9")
                .setSingleAnswer("WIZARD9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w10")
                .setSingleAnswer("WIZARD10")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("w11")
                .setSingleAnswer("WIZARD11")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.WIZARD)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cleric")
                .setSingleAnswer("CLERICMETA"));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl1")
                .setSingleAnswer("CLERIC1")
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .setGold(1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl2")
                .setSingleAnswer("CLERIC2")
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl3")
                .setSingleAnswer("CLERIC3")
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl4")
                .setSingleAnswer("CLERIC4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl5")
                .setSingleAnswer("CLERIC5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl6")
                .setSingleAnswer("CLERIC6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl7")
                .setSingleAnswer("CLERIC7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl8")
                .setSingleAnswer("CLERIC8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl9")
                .setSingleAnswer("CLERIC9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(10, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("cl10")
                .setSingleAnswer("CLERIC10")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(10, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.CLERIC)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("linguistrecruit")
                .setSingleAnswer("LINGUISTRECRUIT")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(12, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(12, Character.values())
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("linguist")
                .setSingleAnswer("LINGUISTMETA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l1")
                .setSingleAnswer("LINGUIST1")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l2")
                .setSingleAnswer("LINGUIST2")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l3")
                .setSingleAnswer("LINGUIST3")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(1, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l4")
                .setSingleAnswer("LINGUIST4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(1, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(3, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l5")
                .setSingleAnswer("LINGUIST5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(3, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l6")
                .setSingleAnswer("LINGUIST6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(7, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l7")
                .setSingleAnswer("LINGUIST7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(7, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l8")
                .setSingleAnswer("LINGUIST8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(7, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(8, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l9")
                .setSingleAnswer("LINGUIST9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(8, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(10, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l10")
                .setSingleAnswer("LINGUIST10")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(10, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(12, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l11")
                .setSingleAnswer("LINGUIST11")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(12, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(14, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("l12")
                .setSingleAnswer("LINGUIST12")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(14, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(15, Character.LINGUIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("economistrecruit")
                .setSingleAnswer("ECONOMISTRECRUIT")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(24, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(24, Character.values())
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("economist")
                .setSingleAnswer("ECONOMISTMETA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e1")
                .setSingleAnswer("ECONOMIST1")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e2")
                .setSingleAnswer("ECONOMIST2")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e3")
                .setSingleAnswer("ECONOMIST3")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(2, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e4")
                .setSingleAnswer("ECONOMIST4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(2, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(4, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e5")
                .setSingleAnswer("ECONOMIST5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(4, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(6, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e6")
                .setSingleAnswer("ECONOMIST6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(4, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(6, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e7")
                .setSingleAnswer("ECONOMIST7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(6, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(8, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("e8")
                .setSingleAnswer("ECONOMIST8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(8, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(11, Character.ECONOMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("chemistrecruit")
                .setSingleAnswer("CHEMISTRECRUIT")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(40, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(40, Character.values())
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("chemist")
                .setSingleAnswer("CHEMISTMETA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch1")
                .setSingleAnswer("CHEMIST1")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch2")
                .setSingleAnswer("CHEMIST2")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch3")
                .setSingleAnswer("CHEMIST3")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(3, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch4")
                .setSingleAnswer("CHEMIST4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(3, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(5, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch5")
                .setSingleAnswer("CHEMIST5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(5, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(7, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch6")
                .setSingleAnswer("CHEMIST6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(5, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(7, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch7")
                .setSingleAnswer("CHEMIST7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(7, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(9, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch8")
                .setSingleAnswer("CHEMIST8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(9, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(11, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("ch9")
                .setSingleAnswer("CHEMIST9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(11, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(14, Character.CHEMIST)
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast")
                .setSingleAnswer("DYNASTMETA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.values())
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .addCharacterLevels(Character.WIZARD, 1)
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast1")
                .setSingleAnswer("DYNAST1")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast2")
                .setSingleAnswer("DYNAST2")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast3")
                .setSingleAnswer("DYNAST3")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast4")
                .setSingleAnswer("DYNAST4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast5")
                .setSingleAnswer("DYNAST5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast6")
                .setSingleAnswer("DYNAST6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast7")
                .setSingleAnswer("DYNAST7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast8")
                .setSingleAnswer("DYNAST8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast9")
                .setSingleAnswer("DYNAST9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast10")
                .setSingleAnswer("DYNAST10")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(5, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dynast11")
                .setSingleAnswer("DYNAST11")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(5, Character.FIGHTER)
                        .build()));

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon")
                .setSingleAnswer("DUNGEONMETA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(18, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(18, Character.values())
                        .build())
                .setSolveRewardProperty(SolveRewardProperty.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .addCharacterLevels(Character.WIZARD, 1)
                        .addCharacterLevels(Character.CLERIC, 1)
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon1")
                .setSingleAnswer("DUNGEON1")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon2")
                .setSingleAnswer("DUNGEON2")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon3")
                .setSingleAnswer("DUNGEON3")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon4")
                .setSingleAnswer("DUNGEON4")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(2, Character.LINGUIST)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon5")
                .setSingleAnswer("DUNGEON5")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.WIZARD)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon6")
                .setSingleAnswer("DUNGEON6")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon7")
                .setSingleAnswer("DUNGEON7")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon8")
                .setSingleAnswer("DUNGEON8")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.LINGUIST)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon9")
                .setSingleAnswer("DUNGEON9")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(5, Character.CLERIC)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon10")
                .setSingleAnswer("DUNGEON10")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(5, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("dungeon11")
                .setSingleAnswer("DUNGEON11")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build()));

        // TODO: add the rest of the rounds

        SolveRewardProperty.Builder solveRewardBuilder = SolveRewardProperty.builder();
        for (Character character : Character.values()) {
            solveRewardBuilder.addCharacterLevels(character, 1);
        }
        SolveRewardProperty oneLevelForEachCharacter = solveRewardBuilder.build();

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("eventa")
                .setSingleAnswer("EVENTA")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveRewardProperty(oneLevelForEachCharacter));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("eventb")
                .setSingleAnswer("EVENTB")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveRewardProperty(oneLevelForEachCharacter));

        solveRewardBuilder = SolveRewardProperty.builder();
        for (Character character : Character.values()) {
            solveRewardBuilder.addCharacterLevels(character, 2);
        }
        SolveRewardProperty twoLevelsForEachCharacter = solveRewardBuilder.build();

        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("eventc")
                .setSingleAnswer("EVENTC")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveRewardProperty(twoLevelsForEachCharacter));
        add.accept(Setec2017PuzzleBuilder.builder()
                .setId("eventd")
                .setSingleAnswer("EVENTD")
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveRewardProperty(twoLevelsForEachCharacter));

        PUZZLES = puzzlesBuilder.build();
    }
}
