package edu.mit.puzzle.cube.huntimpl.setec2017;

import com.google.common.collect.ImmutableMap;

import edu.mit.puzzle.cube.core.model.Puzzle;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.Character;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.Setec2017Puzzle;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.SolveReward;
import edu.mit.puzzle.cube.huntimpl.setec2017.Setec2017HuntDefinition.VisibilityConstraint;

import java.util.function.Consumer;

public class Setec2017Puzzles {
    Setec2017Puzzles() {}

    static final ImmutableMap<String, Setec2017Puzzle> PUZZLES;
    static {
        ImmutableMap.Builder<String, Setec2017Puzzle> puzzlesBuilder = ImmutableMap.builder();
        Consumer<Setec2017Puzzle.Builder> add = puzzleBuilder -> {
            Setec2017Puzzle puzzle = puzzleBuilder.build();
            puzzlesBuilder.put(puzzle.getPuzzle().getPuzzleId(), puzzle);
        };

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("fighter", "FIGHTERMETA")));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f1", "FIGHTER1"))
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .setGold(1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f2", "FIGHTER2"))
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f3", "FIGHTER3"))
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f4", "FIGHTER4"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.FIGHTER)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f5", "FIGHTER5"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.FIGHTER)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f6", "FIGHTER6"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.FIGHTER)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f7", "FIGHTER7"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.FIGHTER)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f8", "FIGHTER8"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.FIGHTER)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f9", "FIGHTER9"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.FIGHTER)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f10", "FIGHTER10"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.FIGHTER)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("f11", "FIGHTER11"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.FIGHTER)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.FIGHTER)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .build()));

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("wizard", "WIZARDMETA")));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w1", "WIZARD1"))
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .setGold(1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w2", "WIZARD2"))
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w3", "WIZARD3"))
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w4", "WIZARD4"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w5", "WIZARD5"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w6", "WIZARD6"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w7", "WIZARD7"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w8", "WIZARD8"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w9", "WIZARD9"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w10", "WIZARD10"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(9, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("w11", "WIZARD11"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(11, Character.WIZARD)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.WIZARD)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.WIZARD, 1)
                        .build()));

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cleric", "CLERICMETA")));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl1", "CLERIC1"))
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .setGold(1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl2", "CLERIC2"))
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl3", "CLERIC3"))
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.CLERIC)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl4", "CLERIC4"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(1, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.CLERIC)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl5", "CLERIC5"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(2, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.CLERIC)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl6", "CLERIC6"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.CLERIC)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl7", "CLERIC7"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(4, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.CLERIC)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl8", "CLERIC8"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.CLERIC)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl9", "CLERIC9"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(7, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(10, Character.CLERIC)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("cl10", "CLERIC10"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(10, Character.CLERIC)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(13, Character.CLERIC)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("linguistrecruit", "LINGUISTRECRUIT"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(12, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(12, Character.values())
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("linguist", "LINGUISTMETA"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l1", "LINGUIST1"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l2", "LINGUIST2"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l3", "LINGUIST3"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(1, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l4", "LINGUIST4"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(1, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(3, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l5", "LINGUIST5"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(3, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l6", "LINGUIST6"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(7, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l7", "LINGUIST7"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(7, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l8", "LINGUIST8"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(7, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(8, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l9", "LINGUIST9"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(8, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(10, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l10", "LINGUIST10"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(10, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(12, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l11", "LINGUIST11"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(12, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(14, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("l12", "LINGUIST12"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(14, Character.LINGUIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("linguist", "UNLOCKED")
                        .addSumConstraint(15, Character.LINGUIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("economistrecruit", "ECONOMISTRECRUIT"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(24, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(24, Character.values())
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("economist", "ECONOMISTMETA"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("e1", "ECONOMIST1"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("e2", "ECONOMIST2"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("e3", "ECONOMIST3"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(2, Character.ECONOMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("e4", "ECONOMIST4"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(2, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(4, Character.ECONOMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("e5", "ECONOMIST5"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(4, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(6, Character.ECONOMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("e6", "ECONOMIST6"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(4, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(6, Character.ECONOMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("e7", "ECONOMIST7"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(6, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(8, Character.ECONOMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("e8", "ECONOMIST8"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(8, Character.ECONOMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("economist", "UNLOCKED")
                        .addSumConstraint(11, Character.ECONOMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.ECONOMIST, 1)
                        .build()));

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("chemistrecruit", "CHEMISTRECRUIT"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(40, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(40, Character.values())
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("chemist", "CHEMISTMETA"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch1", "CHEMIST1"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch2", "CHEMIST2"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch3", "CHEMIST3"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(3, Character.CHEMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch4", "CHEMIST4"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(3, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(5, Character.CHEMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch5", "CHEMIST5"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(5, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(7, Character.CHEMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch6", "CHEMIST6"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(5, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(7, Character.CHEMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch7", "CHEMIST7"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(7, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(9, Character.CHEMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch8", "CHEMIST8"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(9, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(11, Character.CHEMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("ch9", "CHEMIST9"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(11, Character.CHEMIST)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("chemist", "UNLOCKED")
                        .addSumConstraint(14, Character.CHEMIST)
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.CHEMIST, 1)
                        .build()));

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast", "DYNASTMETA"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(6, Character.values())
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .addCharacterLevels(Character.WIZARD, 1)
                        .addCharacterLevels(Character.CLERIC, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast1", "DYNAST1"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.WIZARD)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast2", "DYNAST2"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast3", "DYNAST3"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(2, Character.CLERIC)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast4", "DYNAST4"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.WIZARD)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast5", "DYNAST5"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast6", "DYNAST6"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(3, Character.CLERIC)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast7", "DYNAST7"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.WIZARD)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast8", "DYNAST8"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast9", "DYNAST9"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(4, Character.CLERIC)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast10", "DYNAST10"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(5, Character.WIZARD)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dynast11", "DYNAST11"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dynast", "UNLOCKED")
                        .addSumConstraint(5, Character.FIGHTER)
                        .build()));

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon", "DUNGEONMETA"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(18, Character.values())
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addSumConstraint(18, Character.values())
                        .build())
                .setSolveReward(SolveReward.builder()
                        .addCharacterLevels(Character.FIGHTER, 1)
                        .addCharacterLevels(Character.WIZARD, 1)
                        .addCharacterLevels(Character.CLERIC, 1)
                        .addCharacterLevels(Character.LINGUIST, 1)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon1", "DUNGEON1"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.WIZARD)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon2", "DUNGEON2"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon3", "DUNGEON3"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.CLERIC)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon4", "DUNGEON4"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(2, Character.LINGUIST)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon5", "DUNGEON5"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.WIZARD)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon6", "DUNGEON6"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon7", "DUNGEON7"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.CLERIC)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon8", "DUNGEON8"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(3, Character.LINGUIST)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon9", "DUNGEON9"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(5, Character.CLERIC)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon10", "DUNGEON10"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(5, Character.FIGHTER)
                        .build()));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("dungeon11", "DUNGEON11"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .addPuzzleVisibilityStatusConstraint("dungeon", "UNLOCKED")
                        .addSumConstraint(4, Character.LINGUIST)
                        .build()));

        // TODO: add the rest of the rounds

        SolveReward.Builder solveRewardBuilder = SolveReward.builder();
        for (Character character : Character.values()) {
            solveRewardBuilder.addCharacterLevels(character, 1);
        }
        SolveReward oneLevelForEachCharacter = solveRewardBuilder.build();

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("eventa", "EVENTA"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveReward(oneLevelForEachCharacter));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("eventb", "EVENTB"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveReward(oneLevelForEachCharacter));

        solveRewardBuilder = SolveReward.builder();
        for (Character character : Character.values()) {
            solveRewardBuilder.addCharacterLevels(character, 2);
        }
        SolveReward twoLevelsForEachCharacter = solveRewardBuilder.build();

        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("eventc", "EVENTC"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveReward(twoLevelsForEachCharacter));
        add.accept(Setec2017Puzzle.builder()
                .setPuzzle(Puzzle.create("eventd", "EVENTD"))
                .setVisibleConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setUnlockedConstraint(VisibilityConstraint.builder()
                        .setRequiresManualAction(true)
                        .build())
                .setSolveReward(twoLevelsForEachCharacter));

        PUZZLES = puzzlesBuilder.build();
    }
}
